@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(super_admin, "Super Administrator", "Admin of Supplier Portal")
Person(supplier_admin, "Supplier Administrator", "Admin a supplier account")
Person(employee, "Employee", "Tire Agent employee")
Container(ta, "Tire Agent site", "Ruby on Rails + React.js", "The system for tire sales")

System_Boundary(pp_system, "Supplier Portal System") {
    Container(ip_be_app, "Supplier Portal Backend", "Ruby on Rails", "Provides Supplier Portal functionality via JSON/HTTPS")
    Container(ip_admin_panel, "Supplier Portal Admin Panel", "Ruby on Rails + Hotwire", "Allows admin manage orders, warehouses and suppliers")
    ContainerDb(db, "Database", "PostgresQL", "Stores orders, warehouses and suppliers information")
}

Rel(super_admin, ip_admin_panel, "Manage suppliers accounts and warehouses")
Rel(supplier_admin, ip_admin_panel, "Manages supplier's orders")
Rel(employee, ip_admin_panel, "Manage all orders")
Rel(ip_be_app, db, "Reads and writes", "Rails Active Record ORM")
Rel(ip_admin_panel, ip_be_app, "Uses")
Rel(ta, ip_be_app, "Send orders related with supplier and warehouse", "JSON/HTTPS")
Rel(ip_be_app, ta, "Update order's status", "JSON/HTTPS")

@enduml
