@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Container(ip_dashboard, "Warehouse Portal", "Ruby on Rails + React.js", "Allows users manage Inventory Units")
ContainerDb(db, "Database", "PostgresQL", "Stores Inventory Units and Shipments information")
System_Ext(e_mail, "E-mail system", "System for sending emails")
Container(ta, "Tire Agent site", "Ruby on Rails + React.js", "The system for tire sales")

System_Boundary(ip_system, "Warehouse Portal Backend System") {
    Component(autentification, "Autentification", "Ruby on Rails", "Allows users to sign in, sign up and recovery password")
    Component(inventory_unit, "Inventory Unit", "Ruby on Rails", "Inventory Unit info and its status")
    Component(invoice, "Invoice", "Ruby on Rails", "Invoice image")
    Component(tireagent_connection, "Tire Agent Connection", "Ruby on Rails", "Tire Agent Site Interface")
    Component(portal_api, "API", "Ruby on Rails", "Backend Interface")
    Component(bg_jobs, "Background Jobs", "Ruby on Rails", "Runtime for background tasks")
    Component(warehouse, "Warehouse", "Ruby on Rails", "Warehouse information")
}

Rel(ip_dashboard, warehouse, "Uses", "JSON/HTTPS")
Rel(ip_dashboard, autentification, "Uses", "JSON/HTTPS")
Rel(autentification, bg_jobs, "Sends registration emails")
Rel(bg_jobs, e_mail, "Sends emails")

Rel(inventory_unit, invoice, "Uses")
Rel(warehouse, inventory_unit, "Uses")
Rel(inventory_unit, tireagent_connection, "Update order status callback")

Rel(portal_api, inventory_unit, "Create Inventory Units and update their status")

Rel(tireagent_connection, ta, "Interacting with Tire Agent Site by API", "JSON/HTTPS")
Rel(ta, portal_api, "Interacting with backend", "JSON/HTTPS")

Rel(autentification, db, "Reads and writes", "Rails Active Record ORM")
Rel(inventory_unit, db, "Reads and writes", "Rails Active Record ORM")
Rel(warehouse, db, "Reads and writes", "Rails Active Record ORM")

@enduml
