@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Container(supplier_portal, "Supplier Portal", "Ruby on Rails", "Provides all available suppleirs for Tireagent")
ContainerDb(db, "Database", "PostgresQL", "Stores all infomation")
System_Ext(paypair, "PayPair", "Loans provider")
System_Ext(supplier_portal, "Supplier Portal", "Supplier Portal")
System_Ext(sendgrid, "Email system", "System to send emails")
System_Ext(amazon, "Amazon S3", "Storage")
System_Ext(allstate, "Allstate Protection", "Warranty")
System_Ext(extend, "Extend Protection", "Warranty")

System_Boundary(ta_system, "Tireagent System") {
    Component(orders, "Orders", "Ruby on Rails", "Orders managing")
    Component(shipments, "Shipments", "Ruby on Rails", "Shipments managing")
    Component(payments, "Payments", "Ruby on Rails", "Payments managing")
    Component(fulfillments, "Fulfillments", "Ruby on Rails", "Fulfillment managing")
    Component(warehouses, "Warehouses", "Ruby on Rails", "Warehosues managing")
    Component(products, "Products", "Ruby on Rails", "Products admin panel")
    Component(settings, "Settings", "Ruby on Rails", "Settings for any entity on the site")
    Component(reports, "Repports", "Ruby on Rails", "Reports generating")
    Component(users, "Users", "Ruby on Rails", "Users managing")
}

Rel(ta_system, amazon, "Store files, reports, images", "JSON/HTTPS")
Rel(ta_system, db, "Store data", "Active Record (ORM)")
Rel(fulfillments, supplier_portal, "Communication to fulfill order for specific supplier", "JSON/HTTPS")
Rel(orders, sendgrid, "Sending emails on completing order, delivery status changing etc.,", "JSON/HTTPS")
Rel(orders, allstate, "Creating allstate contract if needed", "JSON/HTTPS")
Rel(orders, extend, "Creating extend contract if needed", "JSON/HTTPS")
Rel(orders, paypair, "Making loan to pay for order", "JSON/HTTPS")
@enduml
