@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Container(ta_fe_ata, "Tireagent application", "Ruby on Rails + React", "Provides all functionality of the Tireagent to end-user via browser")
Container(ta_admin_panel, "Tireagent Admin Panel", "Ruby on Rails", "Allows admin manage orders")
ContainerDb(db, "Database", "PostgresQL", "Stores all infomation")
System_Ext(lenders, "Lenders", "API of different creditors")
System_Ext(sendgrid, "Sms system", "System for sending email")
System_Ext(amazon, "Amazon S3", "Storage")

System_Boundary(ta_system, "Tireagent Backend System") {
    Component(providers, "Providers", "Ruby on Rails", "Communicates with lenders. Sends requests, receives and processes offers")
    Component(users, "Users", "Ruby on Rails", "Allows users to create their loans")
    Component(merchants, "Merchants", "Ruby on Rails", "Allows admin to manage lenders, offers")
    Component(lease_atalications, "Lease Atalications", "Ruby on Rails", "description")
    Component(provider_clients, "Providers client", "Ruby on Rails", "Sends requests to providers")
    Component(autentification, "Autentification", "Ruby on Rails", "Determines if this is a new or returning user")
    Component(opt, "Otp Service", "Ruby on Rails")
    Component(report, "Report Service", "Ruby on Rails", "Send reports")
}

Rel(provider_clients, lenders, "Gets offers form providers", "JSON/HTTPS")
Rel(opt, sms, "Uses", "JSON/HTTPS")

Rel(ta_fe_ata, users, "Uses", "JSON/HTTPS")
Rel(ta_fe_ata, providers, "Uses", "JSON/HTTPS")
Rel(ta_fe_ata, lease_atalications, "Uses", "JSON/HTTPS")
Rel(ta_fe_ata, autentification, "Uses", "JSON/HTTPS")
Rel(users, opt, "Uses", "JSON/HTTPS")

Rel(ta_admin_panel, merchants, "Uses", "JSON/HTTPS")
Rel(ta_admin_panel, users, "Uses", "JSON/HTTPS")
Rel(ta_admin_panel, providers, "Uses", "JSON/HTTPS")
Rel(ta_admin_panel, lease_atalications, "Uses", "JSON/HTTPS")
Rel(ta_admin_panel, autentification, "Uses", "JSON/HTTPS")

Rel(merchants, providers, "Uses", "Object call")

Rel(providers, provider_clients, "Uses", "Object call")

Rel(providers, db, "Reads and writes", "Rails Active Record ORM")
Rel(users, db, "Reads and writes", "Rails Active Record ORM")
Rel(lease_atalications, db, "Reads and writes", "Rails Active Record ORM")
Rel(merchants, db, "Reads and writes", "Rails Active Record ORM")
Rel(providers, db, "Reads and writes", "Rails Active Record ORM")
Rel(autentification, db, "Reads and writes", "Rails Active Record ORM")
Rel(report, amazon, "Users", "JSON/HTTPS")
@enduml
