@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(super_admin, "Super Administrator", "Admin of Supplier portal")
Person(supplier_admin, "Supplier Administrator", "Admin a supplier account")
Person(employee, "Employee", "Tireagent Employee")

Container(supplier_portal, "Supplier Portal", "Ruby on Rails + Hotwire", "The system to handle orders related with supplier by warehouse")
Container(tireagent, "Tire Agent", "Ruby on Rails", "The system to sale tires")

Rel(super_admin, supplier_portal, "Manage suppliers accounts and warehouses")
Rel(supplier_admin, supplier_portal, "Manage supplier's account")
Rel(employee, supplier_portal, "Mange all orders")

Rel(tireagent, supplier_portal, "Send orders related with supplier and warehouse", "JSON/HTTPS")
Rel(supplier_portal, tireagent, "Update order's status", "JSON/HTTPS")

@enduml

